"""Argument parsing, dispatch, and the self-describing `catalog`.

Thin by design: this module decides nothing about fetching, refining or
crawling. It maps arguments onto the concern modules and maps their exceptions
onto exit codes.

`catalog` is generated by walking this parser, never hand-written. A prose flag
list in SKILL.md would drift the first time a default changed and nothing would
catch it; a generated one cannot. That is the single most important structural
property of this CLI: the tool describes itself, and the skill teaches judgment.
"""

import argparse
import json
import sys

from . import config
from .errors import EXIT_CODE_MEANINGS, UltraFetchError, UsageError
from .output import error, silence_library_logging


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="ultra-fetch",
        description="Fetch, crawl and map web pages into clean markdown files.",
    )
    subparsers = parser.add_subparsers(dest="command", metavar="COMMAND")

    # --- fetch --------------------------------------------------------------
    fetch = subparsers.add_parser(
        "fetch", help="Fetch one URL as clean, optionally query-filtered markdown."
    )
    fetch.add_argument("url", help="The page to fetch.")
    fetch.add_argument("--output", metavar="PATH", help="Where to write the result. Default: a predictable temp path.")
    fetch.add_argument("--query", metavar="TEXT", help="Keep only blocks relevant to this query (BM25 fit_markdown).")
    fetch.add_argument("--fast", action="store_true", help="Force the fast static tier; never open a browser.")
    fetch.add_argument("--stealth", action="store_true", help="Force the stealth browser tier (solves Cloudflare).")
    fetch.add_argument("--timeout", type=int, default=config.DEFAULT_TIMEOUT, metavar="SECONDS",
                       help=f"Request timeout in seconds (default {config.DEFAULT_TIMEOUT}; "
                            f"raised to {config.CLOUDFLARE_MIN_TIMEOUT} automatically when solving Cloudflare).")
    fetch.add_argument("--format", choices=("markdown", "text", "html"), default="markdown",
                       help="Output format (default markdown).")
    fetch.add_argument("--no-filter", action="store_true",
                       help="Skip content filtering entirely; emit the whole page.")
    fetch.add_argument("--wait-selector", metavar="CSS",
                       help="Browser tiers only: wait for this CSS selector before capturing.")

    # --- crawl --------------------------------------------------------------
    crawl = subparsers.add_parser(
        "crawl", help="Crawl multiple pages within a site into a directory of markdown files."
    )
    crawl.add_argument("url", help="The URL to start from.")
    crawl.add_argument("--output", metavar="DIR", help="Directory for the pages and manifest.json.")
    crawl.add_argument("--query", metavar="TEXT", help="BM25-filter each page and steer traversal toward relevant links.")
    crawl.add_argument("--max-pages", type=int, default=config.DEFAULT_MAX_PAGES, metavar="N",
                       help=f"Hard cap on pages fetched (default {config.DEFAULT_MAX_PAGES}). Always enforced.")
    crawl.add_argument("--max-depth", type=int, default=config.DEFAULT_MAX_DEPTH, metavar="N",
                       help=f"Link depth from the start URL (default {config.DEFAULT_MAX_DEPTH}). "
                            f"Depth grows exponentially; above 3 is rarely what you want.")
    crawl.add_argument("--include-external", action="store_true", help="Follow off-domain links (default: stay on the domain).")
    crawl.add_argument("--respect-robots", action="store_true", help="Honor robots.txt (default: ignored).")
    crawl.add_argument("--include", action="append", metavar="GLOB", default=[],
                       help="Only crawl URLs matching this glob. Repeatable.")
    crawl.add_argument("--exclude", action="append", metavar="GLOB", default=[],
                       help="Skip URLs matching this glob. Repeatable.")
    crawl.add_argument("--strategy", choices=("best-first", "bfs", "dfs"), default="best-first",
                       help="Traversal order (default best-first).")
    crawl.add_argument("--delay", type=float, default=config.DEFAULT_CRAWL_DELAY, metavar="SECONDS",
                       help=f"Politeness delay between requests (default {config.DEFAULT_CRAWL_DELAY}).")
    crawl.add_argument("--timeout", type=int, default=config.DEFAULT_PAGE_TIMEOUT, metavar="SECONDS",
                       help=f"Per-page timeout (default {config.DEFAULT_PAGE_TIMEOUT}).")

    # --- map ----------------------------------------------------------------
    mapper = subparsers.add_parser(
        "map", help="Discover URLs on a domain without fetching page content."
    )
    mapper.add_argument("domain", help="Domain or URL to map (e.g. example.com).")
    mapper.add_argument("--output", metavar="PATH", help="Where to write the URL list.")
    mapper.add_argument("--query", metavar="TEXT", help="Rank discovered URLs by BM25 relevance to this query.")
    mapper.add_argument("--deep", action="store_true",
                        help="Use the broad multi-source mapper (sitemap, Common Crawl, crt.sh subdomains, "
                             "wayback, path probing) instead of sitemap+CC seeding. Much slower, much broader.")
    mapper.add_argument("--pattern", default="*", metavar="GLOB", help="URL glob filter (default '*').")
    mapper.add_argument("--max-urls", type=int, default=config.DEFAULT_MAX_URLS, metavar="N",
                        help=f"Cap on returned URLs (default {config.DEFAULT_MAX_URLS}).")
    mapper.add_argument("--format", choices=("json", "txt"), default="json",
                        help="json includes scores and metadata; txt is bare URLs (default json).")
    mapper.add_argument("--live-check", action="store_true",
                        help="Verify each URL actually resolves before reporting it. Slower but no dead links.")

    # --- setup --------------------------------------------------------------
    setup = subparsers.add_parser(
        "setup", help="Provision or repair the dedicated venv and browser dependencies."
    )
    setup.add_argument("--browsers", action="store_true", help="Run `scrapling install` and `crawl4ai-setup`.")
    setup.add_argument("--upgrade", action="store_true", help="Upgrade scrapling and crawl4ai, then re-pin requirements.txt.")
    setup.add_argument("--doctor", action="store_true", help="Diagnose the install (crawl4ai-doctor plus a scrapling smoke check).")

    # --- catalog ------------------------------------------------------------
    subparsers.add_parser(
        "catalog", help="Print this CLI's full command, flag and exit-code contract as JSON."
    )

    return parser


def _describe_action(action: argparse.Action) -> dict:
    if isinstance(action, argparse._StoreTrueAction):
        kind = "flag"
    elif action.type is int:
        kind = "int"
    elif action.type is float:
        kind = "float"
    else:
        kind = "str"

    described = {
        "flags": list(action.option_strings) or [action.dest],
        "type": kind,
        "required": bool(action.option_strings) is False,
        "help": action.help or "",
    }
    if action.default is not None and action.default != [] and kind != "flag":
        described["default"] = action.default
    if action.choices:
        described["choices"] = list(action.choices)
    if action.nargs == 0 and isinstance(action, argparse._AppendAction):
        described["repeatable"] = True
    return described


def build_catalog() -> dict:
    """Walk the live parser so the catalog can never disagree with the code."""
    parser = build_parser()
    subparsers_action = next(
        a for a in parser._actions if isinstance(a, argparse._SubParsersAction)
    )

    commands = {}
    for name, sub in subparsers_action.choices.items():
        options = []
        for action in sub._actions:
            if isinstance(action, argparse._HelpAction):
                continue
            options.append(_describe_action(action))
        commands[name] = {
            "help": sub.description or (
                subparsers_action._choices_actions
                and next((c.help for c in subparsers_action._choices_actions if c.dest == name), "")
            ) or "",
            "options": options,
        }

    return {
        "tool": "ultra-fetch",
        "commands": commands,
        "exit_codes": {str(code): meaning for code, meaning in sorted(EXIT_CODE_MEANINGS.items())},
        "output_contract": {
            "stdout": "Nothing substantive. Never parse stdout.",
            "stderr": "Exactly one summary line per successful run, plus any warnings.",
            "artifact": {
                "fetch": "A single markdown/text/html file at --output.",
                "crawl": "A directory at --output containing NNN-<slug>.md per page plus manifest.json.",
                "map": "A JSON array of {url, relevance_score?, head_data?} or newline-delimited URLs at --output.",
            },
            "why": "Results go to a file so the caller controls how much enters its context.",
        },
    }


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if not args.command:
        parser.print_help(sys.stderr)
        return 1

    silence_library_logging()

    try:
        if args.command == "catalog":
            print(json.dumps(build_catalog(), indent=2))
            return 0

        if args.command == "fetch":
            if args.fast and args.stealth:
                raise UsageError("--fast and --stealth are mutually exclusive.")
            from . import fetch as fetch_command

            return fetch_command.run(args)

        if args.command == "crawl":
            from . import crawl as crawl_command

            return crawl_command.run(args)

        if args.command == "map":
            from . import mapper as map_command

            return map_command.run(args)

        if args.command == "setup":
            from . import setup as setup_command

            return setup_command.run(args)

    except UltraFetchError as exc:
        error(str(exc), exc.hint)
        return exc.exit_code
    except KeyboardInterrupt:
        error("interrupted")
        return 1

    raise AssertionError(f"unhandled command {args.command!r}")
